### ISSUE TITLE
Make the CLI backward compatible

### ISSUE THREAD

**Issue by hans-permana** [DeDop/dedop-core#10]
This is a feature request to fix this [bug](https://github.com/DeDop/dedop-core/issues/9).

In the case of re-installation/upgrade, users shall still be able to do processing.

**Comment by mark-ep** [comment]
I will add a new field to the CNF, CHD and CST files called `__metainf__`, containing a description, a version number and a changelog. This will allow the `dedop run` command to reject old files.

There will be a new command `dedop config upgrade` to upgrade existing files to the most recent format.

**Comment by hans-permana** [comment]
fixed by this commit https://github.com/DeDop/dedop-core/commit/bcb80907033c185cdee0c08bdf0dabda8d0bc16b
