### ISSUE TITLE
Error while running DeDop

### ISSUE THREAD

**Issue by AlexaPutnam** [DeDop/dedop-core#14]
Hi, I am a new user and just installed the dedop-core onto a linux. I received the following error while trying to run DeDop, and following the Quick Start instructions (http://dedop.readthedocs.io/en/latest/quickstart.html) using the test_data provided by dedop-core (/dedop-core/test_data/data/test_l1a/inputs/l1a_test.nc):

    raise RuntimeWarning("MAX_ITERS reached in ecef2lla")
RuntimeWarning: MAX_ITERS reached in ecef2lla

Apart from this error, is this DeDop project ready for prime time?

Thank you.

**Comment by mark-ep** [comment]
Hi Alexa,

Thanks for reporting this problem. However, the `l1a_data.nc` file you're processing is intended only for use by one of our unit tests, which checks that the contents of the file are read correctly by DeDop. The data it contains are meaningless, and shouldn't be processed by the rest of the chain.

As for your second question - DeDop is currently under active development, and although the full L1A-to-L1B processing chain is operational, there are some additional features which have not yet been implemented. Whether DeDop is currently suitable for you depends very much on what your needs are, so I don't think this is a question I can answer for you. However, if you decide that it doesn't currently meet your needs, please check back regularly, as we will be releasing updates frequently over the coming weeks and months.

Kind regards,
Mark
