### ISSUE TITLE
Installation from source: Conflict between matplotlib and python 3.6.0-0

### ISSUE THREAD

**Issue by cmray** [DeDop/dedop-core#15]
Hi All,

I was trying to install DeDop  from source following the "Installation from source" instructions.  The process hung with the command 
conda install matplotlib bokeh jupyter ipywidgets

I have included the log of the complete installation process below.

-Chris

CRAY:~ cray$ conda create -n dedop python=3
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /Users/cray/miniconda2/envs/dedop:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2j-0     
    pip:        9.0.1-py36_1 
    python:     3.6.0-0      
    readline:   6.2-2        
    setuptools: 27.2.0-py36_0
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py36_0
    xz:         5.2.2-1      
    zlib:       1.2.8-3      

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#############################################################| 100%
#
# To activate this environment, use:
# > source activate dedop
#
# To deactivate this environment, use:
# > source deactivate dedop
#

CRAY:~ cray$ source activate dedop
(dedop) CRAY:~ cray$ conda install numpy scipy netcdf4
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /Users/cray/miniconda2/envs/dedop:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jpeg-8d                    |                2         145 KB
    curl-7.49.0                |                1         493 KB
    hdf4-4.2.12                |                0         642 KB
    hdf5-1.8.17                |                1         1.7 MB
    libnetcdf-4.4.1            |                0         868 KB
    numpy-1.11.2               |           py36_0         3.3 MB
    netcdf4-1.2.4              |      np111py36_1         550 KB
    scipy-0.18.1               |      np111py36_0        13.5 MB
    ------------------------------------------------------------
                                           Total:        21.1 MB

The following NEW packages will be INSTALLED:

    curl:      7.49.0-1          
    hdf4:      4.2.12-0          
    hdf5:      1.8.17-1          
    jpeg:      8d-2              
    libnetcdf: 4.4.1-0           
    mkl:       11.3.3-0          
    netcdf4:   1.2.4-np111py36_1 
    numpy:     1.11.2-py36_0     
    scipy:     0.18.1-np111py36_0

Proceed ([y]/n)? y

Fetching packages ...
jpeg-8d-2.tar. 100% |##########################################| Time: 0:00:00   2.07 MB/s
curl-7.49.0-1. 100% |##########################################| Time: 0:00:00   2.56 MB/s
hdf4-4.2.12-0. 100% |##########################################| Time: 0:00:00   2.66 MB/s
hdf5-1.8.17-1. 100% |##########################################| Time: 0:00:00   2.74 MB/s
libnetcdf-4.4. 100% |##########################################| Time: 0:00:00   2.56 MB/s
numpy-1.11.2-p 100% |##########################################| Time: 0:00:01   2.40 MB/s
netcdf4-1.2.4- 100% |##########################################| Time: 0:00:00   1.14 MB/s
scipy-0.18.1-n 100% |##########################################| Time: 0:00:05   2.75 MB/s
Extracting packages ...
[      COMPLETE      ]|#############################################################| 100%
Linking packages ...
[      COMPLETE      ]|#############################################################| 100%
(dedop) CRAY:~ cray$ conda install matplotlib bokeh jupyter ipywidgets
Fetching package metadata .......
Solving package specifications: ....

UnsatisfiableError: The following specifications were found to be in conflict:
  - matplotlib
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

(dedop) CRAY:~ cray$

**Comment by cmray** [comment]
Hi All,

I removed the dedop environment and tried again, starting with the command 
CRAY:~ cray$ conda create -n dedop python=3.5

This seems to have avoided the conflict with matplotlib.  

Now I am stuck on the cloning of dedop itself.   I am not familiar with GitHub so am not sure what might be the problem.  I have attached the error message.

-Chris


(dedop) CRAY:~ cray$ git clone https:github.com/DeDop/dedop.git
Cloning into 'dedop'...
ssh: Could not resolve hostname https: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by hans-permana** [comment]
Hi Chris,

Yes, your initial problem seems to be caused by the incompatibility between python 3.6 and matplotlib. I have created a new GitHub issue to trace the fix.

About your following issue, it is also a documentation issue. We have recently changed the repository name to dedop-core, but it still states dedop in the documentation. Use this link instead https://github.com/DeDop/dedop-core.git

**Comment by cmray** [comment]
Hi Hans,

Great.  That fixed it!

Thanks,

Chris

**Comment by cmray** [comment]
Hi Hans,

I'm still having issues with the installation from source. 

After cloning with git and executing "python setup.py develop" i tried to run dedop but get errors.  Should I have installed the Python 3 version of miniconda?

-Chris

CRAY:dedop-core cray$ dedop --help
Traceback (most recent call last):
  File "/Users/cray/miniconda2/bin/dedop", line 11, in <module>
    load_entry_point('dedop', 'console_scripts', 'dedop')()
  File "/Users/cray/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/Users/cray/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/Users/cray/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2258, in load
  File "/Users/cray/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/Users/cray/dedop-core/dedop/ui/cli.py", line 62
    def new_l1b_processor(name: str,
                              ^
SyntaxError: invalid syntax

**Comment by hans-permana** [comment]
Hi Chris,

From what I know, we have only tested the processor with Python 3. @mark-ep can confirm if this is true. Is there a specific reason why you used Python 2?

Hans

**Comment by cmray** [comment]
Hi Hans,

No, I don’t need Python 3, but there was a choice when installing Miniconda and I picked at random.  It might be good to either make sure that the configuration works with either or adjust the installation documentation to indicate which version of Miniconda should be installed. 

I will start over from zero and see if installing the python 3 version of Miniconda fixes the problem. 

Thanks,

Chris

**Comment by hans-permana** [comment]
> There are two variants of the installer: Miniconda is Python 2 based and Miniconda3 is Python 3 based. Note that the choice of which Miniconda is installed only affects the root environment. Regardless of which version of Miniconda you install, you can still install both Python 2.x and Python 3.x environments.
from [Miniconda page](http://conda.pydata.org/miniconda.html)

According to this, if the python version is specified when creating the environment (e.g. `conda create -n dedop python=3`), it should not matter which Miniconda version is installed. From the error log you provided, however, it seems that the python version was not included when creating the new environment (maybe to prevent using python 3.6?). If so, you can try this `conda create -n dedop python=3.5`

Hans

**Comment by cmray** [comment]
I had already tried
> conda create -n dedop python=3.5
> 

from Miniconda2.  This resolved the conflict with matplotlib but lead to the runtime error in dedop.

I wiped the Miniconda2 installation then installed Miniconda3 and reinstalled dedop with the python=3.5 specification.  It seems to have worked, though I have not run any data yet.

Thanks,

-Chris
