### ISSUE TITLE
Quick start guide:  missing pyproj 

### ISSUE THREAD

**Issue by cmray** [DeDop/dedop-core#17]
Hi All,

I am having further difficulty following the quick start guide. 

I did a clean install from source with Miniconda3 and specifying python version 3.5. 
I was able to process L1B and L1Bs outputs but when I used the inspect command in dedop I get the following error in the jupyter window, which indicates that there is a missing file "pyproj"

Is it helpful that I am reporting these issues I am encountering while trying to get dedop running?  Or would it be better if I waited until the project is more mature before giving feedback?

-Chris

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-1f69fc13ac76> in <module>()
----> 1 from dedop.ui.inspect import inspect_l1b_product
      2 get_ipython().magic('matplotlib inline')

/Users/cray/dedop-core/dedop/ui/inspect.py in <module>()
      9 import matplotlib.pyplot as plt
     10 import numpy as np
---> 11 import pyproj
     12 from IPython.display import display
     13 from bokeh.models import ColumnDataSource, Circle

ImportError: No module named 'pyproj'

**Comment by hans-permana** [comment]
Hi Chris,

We are really sorry that you keep stumbling upon one error after another when following our installation guide. Admittedly the installation by source has not been heavily tested. However, I have now tested the installation steps and have verified  that after adding pyproject (`conda install pyproject`) module it should work fine. I have also updated the documentation to reflect this change.

Hans
