### ISSUE TITLE
Allow for easy installing from source code

### ISSUE THREAD

**Issue by forman** [DeDop/dedop-core#18]
Users currently face a problem installing [dedop-core](https://github.com/DeDop/dedop-core) from source using `python3 setup.py install`.

Fix: make the `cate-util` dependency optional, it is used by `dedop-webapi` only, which in turn is only used by [dedop-studio](https://github.com/DeDop/dedop-studio).

**Comment by hans-permana** [comment]
cate-util is also used by the CLI, so at the moment it is not optional

**Comment by hans-permana** [comment]
Instructions have been modified to create a conda env before installing dedop-core from source. This also includes cate-util dependency
