### ISSUE TITLE
[documentation] Information on using CS2-L1A DBL files

### ISSUE THREAD

**Issue by larsonjl** [DeDop/dedop-core#22]
I am a new user and am having trouble figuring out how to input the Cryosat-L1A .DBL files distributed by ESA.  Could you provide some documentation on how to either convert these into the .nc format used by the command line utils or how to use .DBL files directly with the DEDOP command line util.

**Comment by mark-ep** [comment]
Hi, I'm afraid DeDop is only compatible with Sentinel-3 format netCDF files, and cannot read Cryosat .DBL files.

We've released some Cryosat data adapted to the Sentinel-3 format at http://dedop.org/getinvolved/test-datasets/, and we will be adding to that collection in the near future. However, to the best of my knowledge, there are currently no plans to release the code used to perform this adaptation.
