### ISSUE TITLE
Surface Focusing

### ISSUE THREAD

**Issue by mark-ep** [DeDop/dedop-core#23]
Add surface focusing options to the Surface Locations algorithm. This will allow the user to specify a target location (in geodetic coordinates) to which the processor shall create a focused output record.

- [x] update surface locations algorithm (single target)
- [x] add/update CNF parameters (single target)
- [x] unit tests (single target)
- [ ] update surface locations algorithm (sequence of surfaces)
- [ ] add/update CNF parameters (sequence of surfaces)
- [ ] unit tests (sequence of surfaces)

**Comment by hans-permana** [comment]
Hi @mark-ep , have the rest of the tasks been performed? Can this issue be closed?
