### ISSUE TITLE
`--traceback` not enabled for the `run` command

### ISSUE THREAD

**Issue by mark-ep** [DeDop/dedop-core#26]
running `dedop -h` lists an optional `--traceback` flag, which will display the full Python traceback if the processor encounters an error. However, this option isn't enabled on the `dedop run` command, which is where it would be most useful.

running `dedop run --traceback` generates the error:
```
usage: dedop [-h] [--version] [--traceback] [--license] [--docs] COMMAND ...
dedop: error: unrecognized arguments: --traceback
```

**Comment by mzuehlke** [comment]
According to the help the `--traceback` muste be **before** the run command:

    dedop --traceback run

**Comment by mark-ep** [comment]
Oops, sorry! thanks for correcting me.
