### ISSUE TITLE
Handle re-installation over an existing copy

### ISSUE THREAD

**Issue by djbrock** [DeDop/dedop-core#5]
Trying to install a new version over an existing copy lead to the following output:

```
DeDop will now be installed into this location:
/Users/djb/dedop

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below
[/Users/djb/dedop] >>>
/Users/djb/Applications/dedop
ERROR: File or directory already exists: /Users/djb/Applications/dedop
```

Ideally, the installer would detect the existing installation, and offer a mechanism for overwriting without requiring the user to remove the existing installation manually before installing.

The addition of DeDop to the path in .bash_profile is also repeated, even if it already exists.

**Comment by hans-permana** [comment]
@djbrock sorry it took a long time to finally address this issue. 

What you experienced is a default behaviour of constructor, which is a library that we used to create the installer. There is a flag to avoid this error message in case of re-installation (-u). So when you use this command `./DeDop-0.5.1-MacOSX-x86_64.sh -u` it will update the existing software with a new one, and no error message will be displayed.

**Comment by hans-permana** [comment]
About the second issue of repeated entry in the .bash_profile, this is also the behaviour of constructor. I have created an issue on their GitHub page https://github.com/conda/constructor/issues/51
